/*DATABASE CREATION*/
CREATE DATABASE IF NOT EXISTS vparrot_garage;
USE vparrot_garage;


/*CREATION USER ROLE TABLE */
CREATE TABLE IF NOT EXISTS roles
(
  id_role INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  role_name VARCHAR(20) NOT NULL UNIQUE
);
