/*DATABASE CREATION*/
CREATE DATABASE IF NOT EXISTS vparrot_garage;
USE vparrot_garage;


/*CREATION USER ROLE TABLE */
CREATE TABLE IF NOT EXISTS roles
(
  id_role INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  role_name VARCHAR(20) NOT NULL UNIQUE
);

/*CREATION USERS TABLE*/
CREATE TABLE IF NOT EXISTS users
(
  id_user INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  user_email VARCHAR(250) NOT NULL UNIQUE,
  user_password VARCHAR(250) NOT NULL,
  role_id INT NOT NULL,
  FOREIGN KEY (role_id) REFERENCES roles(id_role)
);

/*CREATION TESTIMONIES TABLE*/
CREATE TABLE IF NOT EXISTS testimonies
(
  id_testimony INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  content VARCHAR(250) NOT NULL,
  rating INT NOT NULL,
  is_moderated BOOLEAN NOT NULL
);
